version: '3.8'
services:
  database:
    image: jhojanlopez/inventory_system_db
    container_name: inventory_system_db
    restart: always
    ports:
      - 5432:5432
    networks:
      - app
  eureka:
    image: jhojanlopez/inventory_system_eureka
    container_name: eureka
    ports:
      - 8761:8761
    networks:
      - app
  gateway:
    image: jhojanlopez/inventory_system_gateway
    container_name: gateway
    ports:
      - 8090:8090
    environment:
      - "HOST_EUREKA=eureka:8761"
    depends_on:
      - eureka
    networks:
      - app
  users:
    image: jhojanlopez/inventory_system_users
    container_name: users
    ports:
      - 8080:8080
    environment:
      - "HOST_EUREKA=eureka:8761"
      - "HOST_DB=database:5432"
    depends_on:
      - database
      - eureka
    networks:
      - app
  merchandise:
    image: jhojanlopez/inventory_system_merchandise
    container_name: merchandise
    ports:
      - 8081:8081
    environment:
      - "HOST_EUREKA=eureka:8761"
      - "HOST_DB=database:5432"
      - "MICROSERVICE_URLUSERS=users:8080"
    depends_on:
      - database
      - eureka
      - users
    networks:
      - app
networks:
  app: